### ISSUE TITLE
categories 支持或许bug

### ISSUE THREAD

**Issue by luckrill** [xianmin/hugo-theme-jane#201]
categories 
使用中设置多个分类，比如 categories: ["技术","index"] 
https://www.readmorejoy.com/categories/
只显示一个 技术
并且只有默认的 5个数据
没有看到哪里可以配置
谢谢

**Comment by shaform** [comment]
Hi,
I feel that it might be possible that `index` is a reserved word. Can you try using other names and see if it works?

**Comment by luckrill** [comment]
https://www.xianmin.org/hugo-theme-jane/categories/
 xianmin use index name. the result is same.

**Comment by shaform** [comment]
Thanks for the report. I inspected your site again, it seems that some articles do have multiple categories.

For example, in https://www.readmorejoy.com/2019/06/techgrow/, there are ` 技术` and `人`.  

Also, what did you mean by `只有默认的 5个数据`?

**Comment by luckrill** [comment]
<div class="post-category">
--
  | <a href="https://www.readmorejoy.com/categories/%E6%8A%80%E6%9C%AF/"> 技术 </a>
  | <a href="https://www.readmorejoy.com/categories/%E4%BA%BA/"> 人 </a>
  |  
  | </div>

**Comment by luckrill** [comment]
https://www.readmorejoy.com/categories/
only 5 item

https://www.readmorejoy.com/categories/%E6%8A%80%E6%9C%AF/
normal item

**Comment by shaform** [comment]
I see, you meant that `技术` category only shows 5 articles in the page `https://www.readmorejoy.com/categories/`?

I think that's an intentional design to limit the number of articles displayed. You could click `查看更多 >>>` to expand the list.

To allow customization, we could add a config variable to override the default behavior on this line.
https://github.com/xianmin/hugo-theme-jane/blob/18433ddbbd2cb6442926f822cb5df349680c7fcb/layouts/_default/terms.html#L26 

Or you could modify the template and put it into the `layouts` directory into your site.

**Comment by luckrill** [comment]
OK，this place is I need.

**Comment by luckrill** [comment]
know
