### ISSUE TITLE
如何修改每页里 内容的数量

### ISSUE THREAD

**Issue by luckrill** [xianmin/hugo-theme-jane#270]
比如看到

首页 显示 15个内容
post 页面，一页显示 15个内容
某tag， 一页显示 15个内容

以上这些内容，我需要知道在哪里可以修改？ 根据用户需求做定制

**Comment by luckrill** [comment]
首页数量找到了
config.toml paginate = 15
修改即可，tag 怎么修改昵？

**Comment by midFang** [comment]
@luckrill 
1.可以参考该项目中的 exampleSite/full-config.toml 目录下的文件配置

2.如下这个是我的 config 的配置
[params]
  since = "2020"            # Site creation time          # 站点建立时间
  homeFullContent = false   # if false, show post summaries on home page. Otherwise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary
  archive-paginate = 300    # 归档、标签、分类每页显示的文章数目，建议修改为一个较大的值

**Comment by luckrill** [comment]
know
